server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managesystem?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  redis:
    host: 192.168.19.3
    port: 6379
    password: 123456
    timeout: 0
    lettuce:
      pool:
        max-active: 50
        max-wait: 5000ms

mybatis:
  mapper-locations: classpath:sql/*.xml
  type-aliases-package: com.lhy.management.student
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

